import { Provider as JotaiProvider } from "jotai";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { AppProgressProvider, BaseLayout, CustomToaster, QueryProvider } from "@/shared";

import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-body", display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className} suppressHydrationWarning>
        <AppProgressProvider>
          <QueryProvider>
            <NuqsAdapter>
              <JotaiProvider>
                <BaseLayout>{children}</BaseLayout>
                <CustomToaster />
              </JotaiProvider>
            </NuqsAdapter>
          </QueryProvider>
        </AppProgressProvider>
      </body>
    </html>
  );
}
